apiVersion: v1
kind: Service
metadata:
    name: "ianmbakswk4-33f8"
    labels:
        app: "ianmbakswk4-33f8"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ianmbakswk4-33f8"